# Generated by Django 4.1.3 on 2022-12-11 07:47

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsAccaunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='if user is a superuser,it returns True', verbose_name='superuser status')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, height_field=150, null=True, upload_to=user.models.card_image_location, width_field=150)),
                ('title', models.CharField(max_length=150)),
                ('exprience', models.CharField(max_length=100)),
                ('amount_work', models.IntegerField()),
                ('degree', models.IntegerField()),
                ('text_title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Accaunt',
            fields=[
                ('permissionsaccaunt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.permissionsaccaunt')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=255, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='lastname')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('is_staff', models.BooleanField(default=True, help_text='If user is a staff member, it returns True', verbose_name='is staffman')),
                ('is_active', models.BooleanField(default=True, help_text='If user is active, it returns True', verbose_name='is active')),
                ('is_admin', models.BooleanField(default=False, help_text='If user is admin, it returns True', verbose_name='is admin')),
                ('data_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.permissionsaccaunt', models.Model),
        ),
        migrations.CreateModel(
            name='SubProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=255)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profession')),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
