# Generated by Django 4.1.3 on 2022-12-11 08:01

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='picture',
            field=models.ImageField(height_field=150, upload_to=user.models.card_image_location, width_field=150),
        ),
        migrations.AlterField(
            model_name='profession',
            name='text_title',
            field=models.CharField(max_length=255),
        ),
    ]
