# Generated by Django 4.1.3 on 2022-12-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profession_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='accaunt',
            name='borth_day',
            field=models.DateField(blank=True, null=True, verbose_name='borth_day'),
        ),
    ]
